---
- name: Apply HTTPBIN manifests ACM Hub
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/application.yaml"
  register: httpbin_output

- name: Display HTTPBIN Output
  debug: msg="{{httpbin_output}}"

- name: Apply Placement manifests ACM Hub
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/placement-rule-dev-clusters.yaml"
  register: placement_output

- name: Display Placement Output
  debug: msg="{{placement_output}}"
